### ISSUE TITLE
DRM content not able play after download.

### ISSUE THREAD

**Issue by shindevivek68** [bitmovin/bitmovin-player-ios-samples#14]
@hawk23
We are downloading the DRM content which is working as expected but once it is downloaded we can't play same(downloaded) DRM content in offline.
I request to please verify the source item code while playing the content in offline.

        var playableSourceItem:OfflineSourceItem? {

        let hlsSource = HLSSource(url: self.hls)
        let sourceItem =  SourceItem(hlsSource:hlsSource)

        guard VideoDownloadManager.shared.offlineManager.isPlayableOffline(sourceItem: sourceItem),

            let offlineSourceItem = VideoDownloadManager.shared.offlineManager.createOfflineSourceItem(for: sourceItem, restrictedToAssetCache: true) else {

                //finishWithError(title: "Error", message: "The device seems to be offline, but no offline content for the selected source available.")

                return nil

        }

        

        offlineSourceItem.posterSource = poster

        return offlineSourceItem

    }

_Originally posted by @shindevivek68 in https://github.com/bitmovin/bitmovin-player-ios-samples/issues/13#issuecomment-447843938_

**Comment by hawk23** [comment]
Is the content DRM protected (FairPlay) or unprotected? Also, is the downloading and offline playback working in our [offline content sample app](https://github.com/bitmovin/bitmovin-player-ios-samples/tree/master/BasicOfflinePlayback)?

**Comment by amzadkhan68** [comment]
> Is the content DRM protected (FairPlay) or unprotected? Also, is the downloading and offline playback working in our [offline content sample app](https://github.com/bitmovin/bitmovin-player-ios-samples/tree/master/BasicOfflinePlayback)?

@hawk23  Yes, Content is DRM protected (FairPlay) and We are getting downloading states by OfflineManager after Download. When download is completed, we put device in offline mode and try to play downloaded source item and Player unable to play it.

**Comment by jarhoax** [comment]
Closing due to inactivity.

**Comment by SikanderZeb** [comment]
I'm getting this issue still. Were you able to fix it?

**Comment by jarhoax** [comment]
Offline DRM should be working fine. Can you verify that your content key is persistable? There has to be a content key duration TLLV (or Offline Key TLLV in case of dual expiry) present in the CKC response.

**Comment by temchannat** [comment]
I still have the same problem. Cannot play offline content after download. 

The error mesage is **_[SampleDetailViewController] Download resulted in error: Failed to persist offline content key._**  I follow this [sample](https://github.com/bitmovin/bitmovin-player-ios-samples/tree/master/BasicOfflinePlayback)

**Comment by jarhoax** [comment]
That indicates that your license is most likely not persistable. Please see [comment](https://github.com/bitmovin/bitmovin-player-ios-samples/issues/14#issuecomment-554989276) above for details
